[tool.briefcase]
project_name = "TeenMoons"
bundle = "dev.up7.10moons"
version = "0.0.1"
url = "https://10moons.up7.dev"
license = "MIT license"
author = 'frankjardel'
author_email = "jardelfrank42@gmail.com"

[tool.briefcase.app.teenmoons]
formal_name = "TeenMoons"
description = "Driver for Table 10Moons for Linux"
icon = "src/teenmoons/resources/teenmoons"
sources = ['src/teenmoons', 'src/driver']
requires = [
    'evdev==1.2.0',
    'pyusb==1.0.2',
    'keyboard==0.13.5',
]


[tool.briefcase.app.teenmoons.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev34',
    'std-nslog~=1.0.0',
]

[tool.briefcase.app.teenmoons.linux]
requires = [
    'toga-gtk>=0.3.0.dev34',
    'PyGObject==3.42.1',
]

[tool.briefcase.app.teenmoons.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.teenmoons.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.teenmoons.windows]
requires = [
    'toga-winforms>=0.3.0.dev34',
]

# Mobile deployments
[tool.briefcase.app.teenmoons.iOS]
requires = [
    'toga-iOS>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.teenmoons.android]
requires = [
    'toga-android>=0.3.0.dev34'
]
